---@diagnostic disable: undefined-global
-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.icon-picker")
require("plugins.nullls")
require("plugins.trouble")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.dashboard")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.symbols-outline")
require("plugins.toggleterm")
require("plugins.whichkey")
require("plugins.venv-selector")
