---@diagnostic disable: undefined-global
local function default_header()
	local version = vim.version()
	return {
		"            :h-                                  Nhy`               ",
		"           -mh.                           h.    `Ndho               ",
		"           hmh+                          oNm.   oNdhh               ",
		"          `Nmhd`                        /NNmd  /NNhhd               ",
		"          -NNhhy                      `hMNmmm`+NNdhhh               ",
		"          .NNmhhs              ```....`..-:/./mNdhhh+               ",
		"           mNNdhhh-     `.-::///+++////++//:--.`-/sd`               ",
		"           oNNNdhhdo..://++//++++++/+++//++///++/-.`                ",
		"      y.   `mNNNmhhhdy+/++++//+/////++//+++///++////-` `/oos:       ",
		" .    Nmy:  :NNNNmhhhhdy+/++/+++///:.....--:////+++///:.`:s+        ",
		" h-   dNmNmy oNNNNNdhhhhy:/+/+++/-         ---:/+++//++//.`         ",
		" hd+` -NNNy`./dNNNNNhhhh+-://///    -+oo:`  ::-:+////++///:`        ",
		" /Nmhs+oss-:++/dNNNmhho:--::///    /mmmmmo  ../-///++///////.       ",
		"  oNNdhhhhhhhs//osso/:---:::///    /yyyyso  ..o+-//////////:/.      ",
		"   /mNNNmdhhhh/://+///::://////     -:::- ..+sy+:////////::/:/.     ",
		"     /hNNNdhhs--:/+++////++/////.      ..-/yhhs-/////////::/::/`    ",
		"       .ooo+/-::::/+///////++++//-/ossyyhhhhs/:///////:::/::::/:    ",
		"       -///:::::::////++///+++/////:/+ooo+/::///////.::://::---+`   ",
		"       /////+//++++/////+////-..//////////::-:::--`.:///:---:::/:   ",
		"       //+++//++++++////+++///::--                 .::::-------::   ",
		"       :/++++///////////++++//////.                -:/:----::../-   ",
		"       -/++++//++///+//////////////               .::::---:::-.+`   ",
		"       `////////////////////////////:.            --::-----...-/    ",
		"        -///://////////////////////::::-..      :-:-:-..-::.`.+`    ",
		"         :/://///:///::://::://::::::/:::::::-:---::-.-....``/- -   ",
		"           ::::://::://::::::::::::::----------..-:....`.../- -+oo/ ",
		"            -/:::-:::::---://:-::-::::----::---.-.......`-/.      ``",
		"           s-`::--:::------:////----:---.-:::...-.....`./:          ",
		"          yMNy.`::-.--::..-dmmhhhs-..-.-.......`.....-/:`           ",
		"         oMNNNh. `-::--...:NNNdhhh/.--.`..``.......:/-              ",
		"        :dy+:`      .-::-..NNNhhd+``..`...````.-::-`                ",
		"                        .-:mNdhh:.......--::::-`                    ",
		"                           yNh/..------..`                          ",
		"                                                                    ",
		"N E O V I M - v " .. version.major .. "." .. version.minor,
		"",
	}
end

require("dashboard").setup({
	theme = "doom",
	config = {
		header = default_header(),
		center = {
			{
				icon = "󰙅 ",
				icon_hl = "Title",
				desc = "Open tree",
				desc_hl = "String",
				key = "e",
				keymap = "SPC e",
				key_hl = "Number",
				action = ":Neotree",
			},
			{
				icon = "󰈞 ",
				icon_hl = "Title",
				desc = "Find files",
				desc_hl = "String",
				key = "f",
				keymap = "SPC f f",
				key_hl = "Number",
				action = ":Telescope find_files",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Find text",
				desc_hl = "String",
				key = "w",
				keymap = "SPC f w",
				key_hl = "Number",
				action = ":Telescope live_grep",
			},
			{
				icon = " ",
				icon_hl = "Title",
				desc = "Git Braches",
				desc_hl = "String",
				key = "b",
				keymap = "SPC g b",
				key_hl = "Number",
				action = ":Telescope git_branches",
			},
		},
	},
})
